/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Database.conn;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MrY
 */
public class dataGajiKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form dataGajiKaryawan
     */
    
    conn n = new conn();
    Connection con = n.connection;
    Statement st;
    ResultSet rs;
    String query;
    
    String level = session.getLevel();
    
    public dataGajiKaryawan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        session();
        show_gaji_inJTable();

        
    }
    
    public void session(){
        if(level.equals("admin")){
            jTable2.setEnabled(false);
            btnInsert.setEnabled(false);
        } else if(level.equals("owner")){
           jTable2.setEnabled(true);
        }
    }
    
    public ArrayList<gaji> getGajiList(){
        ArrayList<gaji> gajiList;
        gajiList = new ArrayList<gaji>();
        String query = "SELECT "
                + "data_gaji_karyawan.id_gaji, "
                + "data_karyawan.nik,"
                + "data_karyawan.nama_karyawan,"
                + "jabatan.nama_jabatan,"
                + "data_gaji_karyawan.gaji_pokok "
                + "FROM ((data_gaji_karyawan "
                + "INNER JOIN data_karyawan ON data_gaji_karyawan.id_karyawan = data_karyawan.id_karyawan)"
                + "INNER JOIN jabatan ON data_gaji_karyawan.id_jabatan = jabatan.id_jabatan)";
        
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            gaji Gaji;
            
            while(rs.next()){
                Gaji = new gaji(
                        rs.getInt("id_gaji"),
                        rs.getInt("nik"),
                        rs.getString("nama_karyawan"),
                        rs.getString("nama_jabatan"),
                        rs.getInt("gaji_pokok"));
                gajiList.add(Gaji);
            }
            
        } catch(Exception e){
            e.printStackTrace();
        }
        return gajiList;
    }
    
    public void show_gaji_inJTable(){
        ArrayList<gaji> list = getGajiList();
        
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        
        Object[] row = new Object[5];
        
        
        for(int i = 0; i < list.size(); i++){
            row[0] = list.get(i).getidGaji();
            row[1] = list.get(i).getNIKaryawan();
            row[2] = list.get(i).getNamaKaryawan();
            row[3] = list.get(i).getNamaJabatan();
            row[4] = list.get(i).getGajiPokok();
            model.addRow(row);
        }
        
    }
    
    public void executeSQLQuery(String query, String message) throws SQLException{
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1){
                JOptionPane.showMessageDialog(null, "Data "+message+" Succesfully");
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                show_gaji_inJTable();
            }else{
                JOptionPane.showMessageDialog(this, "Data Not "+message);
            }
        }catch(HeadlessException | SQLException ex){
            ex.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFidGaji = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTFnik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFjabatan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFgaji = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();

        jTFidGaji.setBackground(new java.awt.Color(0, 0, 0));
        jTFidGaji.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jTFidGaji.setBorder(null);
        jTFidGaji.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1020, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(1020, 460));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Gaji", "NIKaryawan", "Nama", "Jabatan", "Gaji Pokok"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTFnik.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jTFnik.setEnabled(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");

        jTFnama.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jTFnama.setEnabled(false);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jTFjabatan.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jTFjabatan.setEnabled(false);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jabatan");

        jTFgaji.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jTFgaji.setEnabled(false);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gaji Pokok");

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N
        btnInsert.setText("Tambah");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFnik, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFnik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTFgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        query = "UPDATE data_gaji_karyawan SET "
                + "gaji_pokok = '"+jTFgaji.getText()+"'"
                + "WHERE id_gaji = '"+ jTFidGaji.getText() +"'";

        try {
            executeSQLQuery(query, "inserted");
        } catch (SQLException ex) {
//            Logger.getLogger(menuBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        
        jTFgaji.enable(true);
        
        jTFidGaji.setText(model.getValueAt(i,0).toString());
        jTFnik.setText(model.getValueAt(i,1).toString());
        jTFnama.setText(model.getValueAt(i,2).toString());
        jTFjabatan.setText(model.getValueAt(i,3).toString());
        jTFgaji.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFgaji;
    private javax.swing.JTextField jTFidGaji;
    private javax.swing.JTextField jTFjabatan;
    private javax.swing.JTextField jTFnama;
    private javax.swing.JTextField jTFnik;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
