/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import login.loginPage;

/**
 *
 * @author MrY
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    Color clickedColor, defaultColor;
    
    String id_log = session.getIdLog();
    String level = session.getLevel();
    
    public MainMenu() {
        initComponents();
      
        clickedColor = new Color(240, 84, 84);
        defaultColor = new Color(48,71,94);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        menRekapAbsensi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuLaporan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuDataKaryawan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuDataGaji = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1110, 560));
        setMinimumSize(new java.awt.Dimension(1110, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1110, 560));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1110, 560));
        jPanel1.setMinimumSize(new java.awt.Dimension(1110, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(240, 84, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PAYROLL");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane2.setMaximumSize(new java.awt.Dimension(1020, 460));
        jDesktopPane2.setMinimumSize(new java.awt.Dimension(1020, 460));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1020, 460));

        jPanel2.setBackground(new java.awt.Color(48, 71, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menRekapAbsensi.setBackground(new java.awt.Color(48, 71, 94));
        menRekapAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menRekapAbsensiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menRekapAbsensiMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(13, 36, 51));
        jLabel4.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accounting_1.png"))); // NOI18N
        jLabel4.setText("Rekap Absensi");

        javax.swing.GroupLayout menRekapAbsensiLayout = new javax.swing.GroupLayout(menRekapAbsensi);
        menRekapAbsensi.setLayout(menRekapAbsensiLayout);
        menRekapAbsensiLayout.setHorizontalGroup(
            menRekapAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menRekapAbsensiLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        menRekapAbsensiLayout.setVerticalGroup(
            menRekapAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(menRekapAbsensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 40));

        menuLaporan.setBackground(new java.awt.Color(48, 71, 94));
        menuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLaporanMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(13, 36, 51));
        jLabel5.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-commodity.png"))); // NOI18N
        jLabel5.setText("Laporan");

        javax.swing.GroupLayout menuLaporanLayout = new javax.swing.GroupLayout(menuLaporan);
        menuLaporan.setLayout(menuLaporanLayout);
        menuLaporanLayout.setHorizontalGroup(
            menuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(52, 52, 52))
        );
        menuLaporanLayout.setVerticalGroup(
            menuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(menuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 140, 40));

        menuDataKaryawan.setBackground(new java.awt.Color(48, 71, 94));
        menuDataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDataKaryawanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDataKaryawanMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(13, 36, 51));
        jLabel6.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add_subnode.png"))); // NOI18N
        jLabel6.setText("Data Karyawan");

        javax.swing.GroupLayout menuDataKaryawanLayout = new javax.swing.GroupLayout(menuDataKaryawan);
        menuDataKaryawan.setLayout(menuDataKaryawanLayout);
        menuDataKaryawanLayout.setHorizontalGroup(
            menuDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        menuDataKaryawanLayout.setVerticalGroup(
            menuDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(menuDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 180, 40));

        menuDataGaji.setBackground(new java.awt.Color(48, 71, 94));
        menuDataGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDataGajiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDataGajiMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(13, 36, 51));
        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add_subnode.png"))); // NOI18N
        jLabel7.setText("Data Gaji");

        javax.swing.GroupLayout menuDataGajiLayout = new javax.swing.GroupLayout(menuDataGaji);
        menuDataGaji.setLayout(menuDataGajiLayout);
        menuDataGajiLayout.setHorizontalGroup(
            menuDataGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDataGajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuDataGajiLayout.setVerticalGroup(
            menuDataGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(menuDataGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close_window.png"))); // NOI18N
        jLabel3.setText("LOG OUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 840, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuLaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanMousePressed
        // TODO add your handling code here:
        menuLaporan.setBackground(clickedColor);
        menuDataKaryawan.setBackground(defaultColor);
        menuDataGaji.setBackground(defaultColor);
        menRekapAbsensi.setBackground(defaultColor);
        
        
    }//GEN-LAST:event_menuLaporanMousePressed

    private void menuDataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataKaryawanMouseClicked
        // TODO add your handling code here:
        dataKaryawan dk = new dataKaryawan();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(dk).setVisible(true);
    }//GEN-LAST:event_menuDataKaryawanMouseClicked

    private void menuDataKaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataKaryawanMousePressed
        // TODO add your handling code here:
        menuLaporan.setBackground(defaultColor);
        menuDataKaryawan.setBackground(clickedColor);
        menuDataGaji.setBackground(defaultColor);
        menRekapAbsensi.setBackground(defaultColor);

    }//GEN-LAST:event_menuDataKaryawanMousePressed

    private void menuDataGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataGajiMouseClicked
        // TODO add your handling code here:
        dataGajiKaryawan dgk = new dataGajiKaryawan();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(dgk).setVisible(true);
        session.set_Level(level);
    }//GEN-LAST:event_menuDataGajiMouseClicked

    private void menuDataGajiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataGajiMousePressed
        // TODO add your handling code here:
        menuLaporan.setBackground(defaultColor);
        menuDataKaryawan.setBackground(defaultColor);
        menuDataGaji.setBackground(clickedColor);
        menRekapAbsensi.setBackground(defaultColor);

    }//GEN-LAST:event_menuDataGajiMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        new MainMenu().setVisible(false);
        session.set_Level(" ");
        new loginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void menRekapAbsensiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menRekapAbsensiMousePressed
        // TODO add your handling code here:
        menuLaporan.setBackground(defaultColor);
        menuDataKaryawan.setBackground(defaultColor);
        menuDataGaji.setBackground(defaultColor);
        menRekapAbsensi.setBackground(clickedColor);
    }//GEN-LAST:event_menRekapAbsensiMousePressed

    private void menuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanMouseClicked
        // TODO add your handling code here:
        laporan lp = new laporan();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(lp).setVisible(true);
    }//GEN-LAST:event_menuLaporanMouseClicked

    private void menRekapAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menRekapAbsensiMouseClicked
        // TODO add your handling code here:
        rekapAbsensi ra = new rekapAbsensi();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(ra).setVisible(true);
    }//GEN-LAST:event_menRekapAbsensiMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainMenu().setVisible(true);
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menRekapAbsensi;
    private javax.swing.JPanel menuDataGaji;
    private javax.swing.JPanel menuDataKaryawan;
    private javax.swing.JPanel menuLaporan;
    // End of variables declaration//GEN-END:variables
}
